### ISSUE TITLE
Forum Reply Preview and Render are inconsistent

### ISSUE THREAD

**Issue by Gambloide** [Nitrino/flatly_light_redmine#54]
Hi,

when writing a reply in a forum the preview shows "blank lines", but after hitting submit the message gets rendered without any line breaks. Example:

**Raw**

```
firstline

secondline
```

**Preview**

```
firstline

secondline
```

**Result**

```
firstline
secondline
```

The problem is _(currently lines 37 - 39 in stylesheets/forum.css)_

``` css
.controller-messages.action-show .message.reply p{
  padding: 0;
}
```

This makes it so that all replies have no line breaks, while only the original message of the thread has them. I don't know if that is intended, but then this should also be represented in the preview.
